### ISSUE TITLE
Docker build uses old Golang version (1.7.5)

### ISSUE THREAD

**Issue by erSitzt** [m-kraus/check_nsc_web#12]
Which results in

`./check_nsc_web.go:292:9: hClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)`

I changed the Dockerfile to

`FROM golang:1.21.6-alpine` 

and i had to add `go mod init` to build.sh because of the `github.com/namsral/flag` import

Btw. is this the correct and up-to-date repo for check_nsc_web ? I just watched Svens talk for a NSClient++ replacement and endet up here in the progress :)

**Comment by m-kraus** [comment]
Hi, as you already guessed: i do not longer maintain this plugin, i handed it over to my former team at Consol. You can find the maintained fork here: https://github.com/ConSol-Monitoring/check_nsc_web

BTW, snclient https://github.com/ConSol-Monitoring/snclient and other goodies are there as well.

Hope i could help you
