### ISSUE TITLE
Isssue while trying to build latest relaese under Ubuntu 18.04

### ISSUE THREAD

**Issue by tbaror** [m-kraus/check_nsc_web#9]
Hello,

When trying to lunch the build.sh i get following output shown below 
any idea what went wrong 
Please advice
Thanks

` ```
./build.sh
+ mkdir -p build/linux/amd64
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -ldflags -s -o build/linux/amd64/check_nsc_web check_nsc_web.go
check_nsc_web.go:18:2: cannot find package "github.com/namsral/flag" in any of:
        /usr/local/go/src/github.com/namsral/flag (from $GOROOT)
        /root/Projects/Proj1/src/github.com/namsral/flag (from $GOPATH)
+ mkdir -p build/linux/386
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=386
+ go build -ldflags -s -o build/linux/386/check_nsc_web check_nsc_web.go
check_nsc_web.go:18:2: cannot find package "github.com/namsral/flag" in any of:
        /usr/local/go/src/github.com/namsral/flag (from $GOROOT)
        /root/Projects/Proj1/src/github.com/namsral/flag (from $GOPATH)
+ mkdir -p build/darwin/amd64
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=amd64
+ go build -ldflags -s -o build/darwin/amd64/check_nsc_web check_nsc_web.go
check_nsc_web.go:18:2: cannot find package "github.com/namsral/flag" in any of:
        /usr/local/go/src/github.com/namsral/flag (from $GOROOT)
        /root/Projects/Proj1/src/github.com/namsral/flag (from $GOPATH)
+ mkdir -p build/windows/amd64
+ CGO_ENABLED=0
+ GOOS=windows
+ GOARCH=amd64
+ go build -ldflags -s -o build/windows/amd64/check_nsc_web.exe check_nsc_web.go
check_nsc_web.go:18:2: cannot find package "github.com/namsral/flag" in any of:
        /usr/local/go/src/github.com/namsral/flag (from $GOROOT)
        /root/Projects/Proj1/src/github.com/namsral/flag (from $GOPATH)
+ mkdir -p build/windows/386
+ CGO_ENABLED=0
+ GOOS=windows
+ GOARCH=386
+ go build -ldflags -s -o build/windows/386/check_nsc_web.exe check_nsc_web.go
check_nsc_web.go:18:2: cannot find package "github.com/namsral/flag" in any of:
        /usr/local/go/src/github.com/namsral/flag (from $GOROOT)
        /root/Projects/Proj1/src/github.com/namsral/flag (from $GOPATH)
`
```

**Comment by m-kraus** [comment]
Thanks for reporting this, should be fixed through 11a421f2bd436b67925e91229dd96485d2e22c68
